{{- define "immich.microservices.hardcodedValues" -}}
global:
  nameOverride: microservices

command: "/bin/sh"
args:
  - "./start-microservices.sh"

service:
  main:
    enabled: false
{{- end }}

{{ if .Values.microservices.enabled }}
{{- $ctx := deepCopy . -}}
{{- $_ := get .Values "microservices" | mergeOverwrite $ctx.Values -}}
{{- $_ = include "immich.microservices.hardcodedValues" . | fromYaml | merge $ctx.Values -}}
{{- include "bjw-s.common.loader.all" $ctx }}
{{ end }}